
-- Load recent sessions
-- map("n", "<leader>sl", "<CMD>SessionLoad<CR>")

-- map("n", "<leader>fs", "<CMD>Telescope file_browser<CR>")
-- find word in the current buffer
-- map("n", "<leader>fb", "<CMD>Telescope buffers<CR>")
-- find word in the current file and other files under the same director
-- change the highlight gscheme
--
-- config for buffer term
-- local buffer_term = require('buffer-term')
-- buffer_term.setup() -- default config
-- vim.keymap.set('t', '<Esc>', '<C-\\><C-n><CMD>b<CR>') -- terminal mode by link esc to exit
-- vim.keymap.set({ 'n', 't'}, '<C-s>', buffer_term.toggle_last)
-- vim.keymap.set({ 'n'}, '<C-s>', function() buffer_term.toggle('s') end)
--
-- toggle terminal
-- map("n", "<C-z>", "<CMD>ToggleTerm<CR>")
-- map("n", "<C-z>", "<C-Bslash><C-n><CMD>ToggleTerm<CR>")
-- map("n", "<C-z>", "<C-Bslash><C-n><CMD>ToggleTerm<CR>")
